print()
greetings = open('hello.txt', 'r')
print(greetings)
print()
print(greetings.read())
print()
greetings.close()
f = open('hello.txt', 'r')
print("File name: ", f.name)
print("File mode: ", f.mode)
contents = f.read()
print("Contents: ", contents)
print("Is file closed? ", f.closed)
f.close()
print("Is file closed? ", f.closed)
print()
newFile = open('newfile.txt', 'w')
print(newFile)
newFile.write("This is a new file created using python.")
newFile.close()
print()
fileOR = open('newFile.txt', 'w')
fileOR.write("The contents of the newFile is now changed.")
fileOR.close()
print()
appendFile = open("hello.txt", 'a')
appendFile.write("\n\nDon't forget to smile today :)")
appendFile.close()

with open("hello.txt", 'r') as f:
    contents = f.read()
    print(contents)
print()